name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: myapp
  TAG: ${{ env.GITHUB_SHA }}
  TRIVY_VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker build
      uses: actions/checkout@v3
      env:
        CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      run: |
        docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD
        docker build -t myapp:$TAG app
        docker push myapp:$TAG

  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trivy scan
      uses: actions/checkout@v3
      env:
        CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        TRIVY_VERSION: ${{ env.TRIVY_VERSION }}
      run: |
        docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD
        docker pull myapp:$TAG
        trivy image --exit-code 0 --no-progress myapp:$TAG

    - name: Kube-linter scan
      uses: actions/checkout@v36
      run: |
        docker run -v kubelinter-config.yaml:/etc/config.yaml -v k8s:/dir stackrox/kube-linter lint /dir --config /etc/config.yaml || true
