name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: myapp
  DOCKER_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USER }}
  DOCKER_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ContainerRegistry
    
    steps:
    - name: List
      run: |
        ls -la
    - name: Checkout Code
      uses: actions/checkout@v2     
    - name: Docker build and push
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t $IMAGE_NAME:$GITHUB_RUN_ID app
        docker push $IMAGE_NAME:$GITHUB_RUN_ID

  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trivy scan
      run: |
        wget --no-verbose https://github.com/aquasecurity/trivy/archive/refs/tags/v0.37.0.tar.gz -O - | tar -zxvf -
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker pull $IMAGE_NAME:$GITHUB_RUN_ID
        trivy image --exit-code 0 --no-progress $IMAGE_NAME:$GITHUB_RUN_ID

    - name: Kube-linter scan
      run: |
        find . -name kubelinter-config.yaml
        docker run -v kubelinter-config.yaml:/etc/config.yaml -v k8s:/dir stackrox/kube-linter lint /dir --config /etc/config.yaml || true
