name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  CONTAINER_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USER }}
  CONTAINER_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ContainerRegistry
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Docker build and push
      run: |
        docker build -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_RUN_ID app/
        echo "$CONTAINER_PASSWORD" | docker login ghcr.io -u "$CONTAINER_USERNAME" --password-stdin
        wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
        sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
        trivy image --exit-code 1 --severity CRITICAL --no-progress ghcr.io/$GITHUB_REPOSITORY:$GITHUB_RUN_ID
        docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_RUN_ID
        echo $GITHUB_REPOSITORY:$GITHUB_RUN_ID
